function trial_data = read_trials_timetable(nwbFilePath)
% read_trials_timetable - Read table with trials data

    import bot.internal.nwb.table_from_datasets_new

    trial_data = table_from_datasets_new(nwbFilePath, '/intervals/trials');
    
    % Process some of the columns for better representation

    time_variables = [ ...
        "start_time", ...
        "stop_time" ...
        ];

    % Todo: include change_time / change_time_no_display_delay and
    % trial_length?

    boolean_variables = [ ...
        "aborted", ...
        "auto_rewarded", ...
        "catch", ...
        "correct_reject", ...
        "false_alarm", ...
        "go", ...
        "hit", ...
        "is_change", ...
        "miss"];

    for time_variable = time_variables
        trial_data.(time_variable) = seconds( trial_data.(time_variable) );
    end

    for boolean_variable = boolean_variables
        trial_data.(boolean_variable) = strcmpi( trial_data.(boolean_variable), 'true' );
    end
    
    % Specify column order
    column_order = { ...
        'id', ...
        'start_time', ...
        'stop_time', ...
        'initial_image_name', ...
        'change_image_name', ...
        'is_change', ...
        'change_time_no_display_delay', ... % Only VB Ephys
        'change_time', ... % Only VB Ophys
        'go', ...
        'catch', ...
        'lick_times', ...
        'response_time', ...
        'response_latency',... % Only VB Ophys
        'reward_time', ...
        'reward_volume', ...
        'hit', ...
        'false_alarm', ...
        'miss', ...
        'correct_reject', ...
        'aborted', ...
        'auto_rewarded', ...
        'change_frame', ...
        'trial_length' ...
    };
    
    column_order = intersect(column_order, trial_data.Properties.VariableNames, 'stable');

    trial_data = trial_data(:, column_order);
end
