% hardcoded session_by_stimuli, there is no such thing in any manifest,
% they hardcoded it in allensdk/brain_observatory/stimulus_info.py too.

function session_by_stimuli = get_session_by_stimuli()
session_by_stimuli.three_session_A = {'drifting_gratings','natural_movie_one','natural_movie_three','spontaneous_activity'};
session_by_stimuli.three_session_B = {'static_gratings','natural_scene','natural_movie_one','spontaneous_activity'};
session_by_stimuli.three_session_C = {'locally_sparse_noise_four_degree','natural_movie_one','natural_movie_two','spontaneous_activity'};
session_by_stimuli.three_session_C2 = {'locally_sparse_noise_four_degree','locally_sparse_noise_eight_degree', ...
    'natural_movie_one','natural_movie_two','spontaneous_activity'};
end

% still don't know why these two formats don't work, get yelled for array dimensions

% session_by_stimuli = struct('three_session_A',{'drifting_gratings','natural_movie_one','natural_movie_three','spontaneous_activity'},...
%     'three_session_B',{'static_gratings','natural_scene','natural_movie_one','spontaneous_activity'},...
%     'three_session_C', {'locally_sparse_noise_four_degree','natural_movie_one','natural_movie_two','spontaneous_activity'},...
%     'three_session_C2', {'locally_sparse_noise_four_degree','locally_sparse_noise_eight_degree', ...
%     'natural_movie_one','natural_movie_two','spontaneous_activity'})

% three_session_A = {'drifting_gratings','natural_movie_one','natural_movie_three','spontaneous_activity'}
% three_session_B = {'static_gratings','natural_scene','natural_movie_one','spontaneous_activity'}
% three_session_C = {'locally_sparse_noise_four_degree','natural_movie_one','natural_movie_two','spontaneous_activity'}
% three_session_C2 = {'locally_sparse_noise_four_degree','locally_sparse_noise_eight_degree', ...
%     'natural_movie_one','natural_movie_two','spontaneous_activity'}
% session_by_stimuli = struct('three_session_A',three_session_A...
%     ,'three_session_B',three_session_B...
%     ,'three_session_C', three_session_C...
%     ,'three_session_C2', three_session_C2)
