function event(strTrackingID, strUserID, strClientUUID, varargin)

% event - FUNCTION Send an 'event' hit type to Google Analytics
%
% Usage: event(strTrackingID, strUserID, strClientUUID, ...
%              < strEventCategory, strEventAction, strEventLabel, nEventValue, ...
%              strAppName, strAppVersion, ...
%              strDataSource, strSessionControl, bNonInteractive >)
%
% `strTrackingID` must be a valid Google Analytics tracking ID.
% Only one of `strUserID` and `strClientUUID` is required.
%
% Other arguments are optional. See Google Analytics Measurement Protocol
% documentation for details:
% https://developers.google.com/analytics/devguides/collection/protocol/v1/

% - Call the 'collect' interface with an 'event' hit type
bot.internal.ga.collect(strTrackingID, 'event', ...
   strUserID, strClientUUID, ...
   [], [], [], [], ...
   [], ...
   varargin{:});