function metadata = readTaskMetadata(nwbFileName)
% readTaskMetadata - Read ophys metadata from an NWB file

    import bot.internal.nwb.readAttributesToStruct

    ATTRIBUTES_MAPPING = struct(...
        'stimulus_duration_sec', {{'/general/task_parameters', 'stimulus_duration_sec' }}, ...
        'response_window_sec', {{'/general/task_parameters', 'response_window_sec' }}, ...
        'reward_volume', {{'/general/task_parameters', 'reward_volume' }}, ...
        'session_type', {{'/general/task_parameters', 'session_type' }}, ...
        'stimulus', {{'/general/task_parameters', 'stimulus' }}, ...
        'n_stimulus_frames', {{'/general/task_parameters', 'n_stimulus_frames' }}, ...
        'task', {{'/general/task_parameters', 'task' }}, ...
        'omitted_flash_fraction', {{'/general/task_parameters', 'omitted_flash_fraction' }}, ...
        'blank_duration_sec', {{'/general/task_parameters', 'blank_duration_sec' }}, ...
        'stimulus_name', {{'/general/task_parameters', 'stimulus_name' }}, ...
        'auto_reward_volume', {{'/general/task_parameters', 'auto_reward_volume' }}, ...
        'stimulus_distribution', {{'/general/task_parameters', 'stimulus_distribution' }} ); 

    metadata = readAttributesToStruct(nwbFileName, ATTRIBUTES_MAPPING);
end
